"""
Response cleaner.

This module removes internal reasoning blocks and unnecessary
whitespace from Large Language Model (LLM) responses before they
are returned to the client.
"""

import re

from app.core.logger import logger


THINK_BLOCK_PATTERN = re.compile(
    r"<think>.*?</think>",
    re.DOTALL,
)


def clean_response(response: str) -> str:
    """
    Clean the raw response returned by the language model.

    This function removes:
    - <think>...</think> reasoning blocks
    - Leading and trailing whitespace

    Parameters
    ----------
    response : str
        Raw response generated by the language model.

    Returns
    -------
    str
        Cleaned response suitable for the end user.
    """

    if not response:
        logger.warning(
            "Received an empty response from the language model."
        )
        return ""

    logger.info("Cleaning language model response.")

    logger.debug(
        "Raw response length: %d",
        len(response),
    )

    cleaned_response = THINK_BLOCK_PATTERN.sub(
        "",
        response,
    ).strip()

    logger.debug(
        "Cleaned response length: %d",
        len(cleaned_response),
    )

    logger.info("Language model response cleaned successfully.")

    return cleaned_response