"""
Response cleaner.

This module removes internal reasoning blocks and unnecessary
whitespace from Large Language Model (LLM) responses before they
are returned to the client.
"""

import re

from app.core.logger import logger


def clean_response(response: str) -> str:
    """
    Clean the raw response returned by the language model.

    This function removes:
    - <think>...</think> reasoning blocks
    - Leading and trailing whitespace

    Parameters
    ----------
    response : str
        Raw response generated by the language model.

    Returns
    -------
    str
        Cleaned response suitable for the end user.
    """

    if not response:
        logger.warning("Received an empty response from the language model.")
        return ""

    logger.info("Cleaning language model response.")

    # Temporary debugging logs
    logger.info("Raw response length: %d", len(response))
    logger.debug("Raw response:\n%s", response)

    cleaned_response = re.sub(
        pattern=r"<think>.*?</think>",
        repl="",
        string=response,
        flags=re.DOTALL,
    )

    cleaned_response = cleaned_response.strip()

    # Temporary debugging logs, below two lines are commented out after testing test_api.py
    # logger.info("Cleaned response length: %d", len(cleaned_response))
    # logger.debug("Cleaned response:\n%s", cleaned_response)

    logger.info("Language model response cleaned successfully.")

    return cleaned_response